check-mutex:
	 go run mutex/main.go $(LIMIT) | python3 check.py $(LIMIT)
check-condition:
	 go run condition/main.go $(LIMIT) | python3 check.py $(LIMIT)
check-semaphore:
	 go run semaphore/main.go $(LIMIT) | python3 check.py $(LIMIT)
